sonar.projectKey=project-4-thai-weather-app
sonar.projectName=Project-4 Thai Weather App
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.expo/**,backend/generated/**,frontend/dist/**,**/*.env,**/.env,**/.env.*
sonar.javascript.node.maxspace=4096
